# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dependency Scanning

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '41 19 * * 3'

jobs:

  dependency-scan:

    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Scan Clojure dependencies
        uses: clj-holmes/clj-watson-action@v4.0.1
        with:
          database-strategy: github-advisory
          aliases: clojure-lsp,test
          deps-edn-path: deps.edn
          suggest-fix: true
          output-type: sarif
          output-file: cljure-results.sarif
          fail-on-result: false

      - name: Upload Clojure results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: cljure-results.sarif
      
      - name: Scan Python dependencies
        uses: pyupio/pyup-action@v1
        with:
          sarif_file: python-results.sarif
      
      - name: Upload Python results  
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: python-results.sarif

      - name: Scan JavaScript dependencies
        uses: Snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=js-results.sarif
          
      - name: Upload JavaScript results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: js-results.sarif
