# Enhanced Dependabot configuration for automated dependency management
version: 2
updates:
  # Ruby/Bundler dependencies
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "@dependabot"
    assignees:
      - "@dependabot"
    commit-message:
      prefix: "🔄 bundler"
      prefix-development: "🔄 bundler-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "ruby"
      - "automated"
    ignore:
      # Ignore major version updates for stable gems
      - dependency-name: "jekyll"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sass"
        update-types: ["version-update:semver-major"]
    groups:
      jekyll-ecosystem:
        patterns:
          - "jekyll*"
          - "liquid*"
          - "kramdown*"
      testing-tools:
        patterns:
          - "rspec*"
          - "minitest*"
          - "test-unit*"

  # NPM dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "@dependabot"
    assignees:
      - "@dependabot"
    commit-message:
      prefix: "🔄 npm"
      prefix-development: "🔄 npm-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
      - "automated"
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      - dependency-name: "webpack"
        update-types: ["version-update:semver-major"]
    groups:
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
      build-tools:
        patterns:
          - "webpack*"
          - "babel*"
          - "@babel/*"
          - "typescript"
          - "ts-*"
      testing-framework:
        patterns:
          - "jest*"
          - "@testing-library/*"
          - "cypress*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "🔄 actions"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    groups:
      core-actions:
        patterns:
          - "actions/*"
      deployment-actions:
        patterns:
          - "*deploy*"
          - "*pages*"

  # Docker (if applicable)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "🔄 docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "automated"